### ISSUE TITLE
Not rendering in internet explorer

### ISSUE THREAD

**Issue by dragonrm** [leonaard/icalendar2fullcalendar#19]
Having an issue with IE9+ rendering the calendar. It works with every other browser that I've tested though. If I wasn't using it for a client I would care but he does. 

Thanks

Jason

**Comment by leonaard** [comment]
To use with IE, please see https://github.com/leonaard/icalendar2fullcalendar/pull/20

**Comment by leonaard** [comment]
Should be solved by fce06a675f6059fca3901100a0259b9c6a86ac01.
Please reopen if not.
